### ISSUE TITLE
SLR not scraping

### ISSUE THREAD

**Issue by anon55661** [xbapps/xbvr#1815]
None of the SLR websites seem to be scraping. Using version 0.4.28

**Comment by pops64** [comment]
SLR has a max connection limit now. Ensure you set the `--concurrent_scrapers` to four or less

**Comment by Holywayyne** [comment]
Where would I find the Concurrent Scrapers setting to change it to four or less?

**Comment by anon55661** [comment]
Can we add a new version with concurrent scrapers fixed for SLR please

**Comment by Havok456** [comment]
i am using the windows version i do not see a setting for this how do i add --concurrent_scrapers to xbvr?

**Comment by pops64** [comment]
> Can we add a new version with concurrent scrapers fixed for SLR please

It already is fixed. You just have to launch XBVR with the option turned on

> i am using the windows version i do not see a setting for this how do i add --concurrent_scrapers to xbvr?

https://github.com/xbapps/xbvr/blob/master/README.md at the bottom are the instructions for using launch variables

**Comment by anon55661** [comment]
Still not working with concurrent scrapers set to anything under 4.

**Comment by pops64** [comment]
Is this the error your getting? #1779 Then you more than likely can't connect to SLR from your machine running XBVR

**Comment by moToroTor** [comment]
> @Havok456 https://github.com/xbapps/xbvr/blob/master/README.md It is a launch option. You have to run XBVR through the CLI for it

This option isn't available for the Docker build yet.

**Comment by pops64** [comment]
Like I said in #1835

Docker you can use the environmental variable the launch command sets. Append this to other -e switches if present for docker.

https://docs.docker.com/compose/environment-variables/set-environment-variables/
https://docs.docker.com/reference/cli/docker/container/run/#env

**Comment by anon55661** [comment]
Fixed by using a VPN before scraping.
