### ISSUE TITLE
All VirtualRealPorn scenes overwritten with the same cast

### ISSUE THREAD

**Issue by 4gnusd3i** [xbapps/xbvr#749]
**Problem**: After recent scrape, all scenes scraped from VirtualRealPorn have the same cast (Charlotte Sartre).
**Attempted resolution**: Clearing all scraped scenes and/or forcing update scenes gives same result.

**Comment by omdbapi** [comment]
Same issue except the cast on mine is "Jillian Janson".

**Comment by theRealKLH** [comment]
most likely resolved in #730

**Comment by 4gnusd3i** [comment]
> most likely resolved in #730

Its merged into master and released now right?
Because I still have the same issues with some scenes

**Comment by CoolMintChocolate** [comment]
> > most likely resolved in #730
> 
> Its merged into master and released now right? Because I still have the same issues with some scenes

VRP changed their cast page again after my PR was merged. @theRealKLH does have a fix for it but I haven't had time to double check it yet. If you're nice to him maybe he'll open a PR for it 😛
